### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by roiiiu** [koichi-murakami/g4python#4]
In file included from /Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:26:
/opt/homebrew/include/pybind11/operators.h:124:67: error: use of overloaded operator '==' is ambiguous (with operand types 'const G4String' and 'const std::string')
PYBIND11_BINARY_OPERATOR(eq,        eq,           operator==,   l == r)
                                                                ~ ^  ~
/opt/homebrew/include/pybind11/operators.h:77:61: note: expanded from macro 'PYBIND11_BINARY_OPERATOR'
    static auto execute(const L &l, const R &r) -> decltype(expr) { return (expr); }   \
                                                            ^~~~
/opt/homebrew/include/pybind11/operators.h:52:16: note: in instantiation of template class 'pybind11::detail::op_impl<pybind11::detail::op_eq, pybind11::detail::op_l, G4String, G4String, std::string>' requested here
        cl.def(op::name(), &op::execute, is_operator(), extra...);
               ^
/opt/homebrew/include/pybind11/pybind11.h:1395:12: note: in instantiation of function template specialization 'pybind11::detail::op_<pybind11::detail::op_eq, pybind11::detail::op_l, pybind11::detail::self_t, std::string>::execute<pybind11::class_<G4String>>' requested here
        op.execute(*this, extra...);
           ^
/Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:43:4: note: in instantiation of function template specialization 'pybind11::class_<G4String>::def<pybind11::detail::op_eq, pybind11::detail::op_l, pybind11::detail::self_t, std::string>' requested here
  .def(py::self == std::string())
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/string:4045:1: note: candidate function [with _Allocator = std::allocator<char>]
operator==(const basic_string<char, char_traits<char>, _Allocator>& __lhs,
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/string:4033:1: note: candidate function [with _CharT = char, _Traits = std::char_traits<char>, _Allocator = std::allocator<char>]
operator==(const basic_string<_CharT, _Traits, _Allocator>& __lhs,
^
/Users/roy/Downloads/geant4.11.00.b01/install/bin/../include/Geant4/G4String.icc:114:25: note: candidate function
inline G4bool G4String::operator==(const G4String& str) const
                        ^
In file included from /Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:26:
/opt/homebrew/include/pybind11/operators.h:52:33: error: no member named 'execute' in 'pybind11::detail::op_impl<pybind11::detail::op_eq, pybind11::detail::op_l, G4String, G4String, std::string>'
        cl.def(op::name(), &op::execute, is_operator(), extra...);
                            ~~~~^
/opt/homebrew/include/pybind11/pybind11.h:1395:12: note: in instantiation of function template specialization 'pybind11::detail::op_<pybind11::detail::op_eq, pybind11::detail::op_l, pybind11::detail::self_t, std::string>::execute<pybind11::class_<G4String>>' requested here
        op.execute(*this, extra...);
           ^
/Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:43:4: note: in instantiation of function template specialization 'pybind11::class_<G4String>::def<pybind11::detail::op_eq, pybind11::detail::op_l, pybind11::detail::self_t, std::string>' requested here
  .def(py::self == std::string())
   ^
In file included from /Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:26:
/opt/homebrew/include/pybind11/operators.h:125:67: error: use of overloaded operator '!=' is ambiguous (with operand types 'const G4String' and 'const std::string')
PYBIND11_BINARY_OPERATOR(ne,        ne,           operator!=,   l != r)
                                                                ~ ^  ~
/opt/homebrew/include/pybind11/operators.h:77:61: note: expanded from macro 'PYBIND11_BINARY_OPERATOR'
    static auto execute(const L &l, const R &r) -> decltype(expr) { return (expr); }   \
                                                            ^~~~
/opt/homebrew/include/pybind11/operators.h:52:16: note: in instantiation of template class 'pybind11::detail::op_impl<pybind11::detail::op_ne, pybind11::detail::op_l, G4String, G4String, std::string>' requested here
        cl.def(op::name(), &op::execute, is_operator(), extra...);
               ^
/opt/homebrew/include/pybind11/pybind11.h:1395:12: note: in instantiation of function template specialization 'pybind11::detail::op_<pybind11::detail::op_ne, pybind11::detail::op_l, pybind11::detail::self_t, std::string>::execute<pybind11::class_<G4String>>' requested here
        op.execute(*this, extra...);
           ^
/Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:45:4: note: in instantiation of function template specialization 'pybind11::class_<G4String>::def<pybind11::detail::op_ne, pybind11::detail::op_l, pybind11::detail::self_t, std::string>' requested here
  .def(py::self != std::string())
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/string:4090:1: note: candidate function [with _CharT = char, _Traits = std::char_traits<char>, _Allocator = std::allocator<char>]
operator!=(const basic_string<_CharT,_Traits,_Allocator>& __lhs,
^
/Users/roy/Downloads/geant4.11.00.b01/install/bin/../include/Geant4/G4String.icc:126:25: note: candidate function
inline G4bool G4String::operator!=(const G4String& str) const
                        ^
In file included from /Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:26:
/opt/homebrew/include/pybind11/operators.h:52:33: error: no member named 'execute' in 'pybind11::detail::op_impl<pybind11::detail::op_ne, pybind11::detail::op_l, G4String, G4String, std::string>'
        cl.def(op::name(), &op::execute, is_operator(), extra...);
                            ~~~~^
/opt/homebrew/include/pybind11/pybind11.h:1395:12: note: in instantiation of function template specialization 'pybind11::detail::op_<pybind11::detail::op_ne, pybind11::detail::op_l, pybind11::detail::self_t, std::string>::execute<pybind11::class_<G4String>>' requested here
        op.execute(*this, extra...);
           ^
/Users/roy/Downloads/g4python-main/source/global/pyG4String.cc:45:4: note: in instantiation of function template specialization 'pybind11::class_<G4String>::def<pybind11::detail::op_ne, pybind11::detail::op_l, pybind11::detail::self_t, std::string>' requested here
  .def(py::self != std::string())
   ^
4 errors generated.

**Comment by koichi-murakami** [comment]
Can you show the output of cmake command?

**Comment by roiiiu** [comment]
-- Found Geant4: /Users/roy/Downloads/geant4.11.00.b01/install/bin/.. (11.0.0)
-- Geant4 Visualization: true
-- Geant4 GDML: true
-- Found pybind11: /opt/homebrew/include (found version "2.8.1" )
-- --------------------------------------------------------
-- Parameters for building
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- CMAKE_INSTALL_PREFIX: /Users/roy/opt/geant4/geant4py-11.0.0
-- GEANT4_VERSION: 11.0.0
-- GEANT4_LIBRARY_DIR: /Users/roy/Downloads/geant4.11.00.b01/install/bin/../lib
-- Python3_EXECUTABLE: /Users/roy/miniforge3/bin/python3.9
-- PYTHON3_INCLUDE_DIRS: /Users/roy/miniforge3/include/python3.9
-- pybind11_VERSION: 2.8.1
-- pybind11_INCLUDE_DIR: /opt/homebrew/include
-- --------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/roy/Downloads/g4python-main/build

**Comment by koichi-murakami** [comment]
You use the beta version of geant4 v11.0. The implementation of G4String is changed in the 11.0 release.
We will release v11.0 shortly. please wait for the new release.
